Massive docker talk upgrade
New conda environment. New devices for offline vocal interaction. Added cuda

diff --git a/docker_stuff/docker_talk/Dockerfile b/docker_stuff/docker_talk/Dockerfile
--- a/docker_stuff/docker_talk/Dockerfile
+++ b/docker_stuff/docker_talk/Dockerfile
@@ -10,6 +10,7 @@ ARG uid="1000"
 ARG gid="1000"
 ARG vcpkg_tag="tags/2025.01.13"
 ARG tour_branch="jazzy"
+ARG cuda_version="12.8"
 
 # Non-interactive installation mode
 ENV DEBIAN_FRONTEND=noninteractive \
@@ -49,26 +50,56 @@ RUN useradd -l -u 33334 -G sudo -md /home/${user_name} -s /bin/bash -p ${user_na
 
 # Set ENV
 USER ${user_name}
-RUN sudo mkdir ${robot_code}
 ENV robotology_install_user=${user_name} \
     yarp_user_home=/home/${user_name} \
     robot_code=${robot_code}
+RUN sudo mkdir ${robot_code} && mkdir ${yarp-user_home}/Downloads && \
+    mkdir ${yarp-user_home}/userInstalled
 RUN sudo chown -R ${robotology_install_user}:${robotology_install_user} ${robot_code}
 
-# Miniforge installation
-USER ${robotology_install_user}
-WORKDIR ${yarp_user_home}
-RUN wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
-RUN /bin/bash -c "bash ${yarp_user_home}/Miniforge3-$(uname)-$(uname -m).sh -b"
-RUN ${yarp_user_home}/miniforge3/bin/conda init
-RUN /bin/bash -c "source ${yarp_user_home}/miniforge3/etc/profile.d/conda.sh && \
-    conda create -y -n openwakeword python=3.11 && \
-    conda clean -afy"
-RUN /bin/bash -c "source ${yarp_user_home}/miniforge3/etc/profile.d/conda.sh && \
-    conda activate openwakeword && \
-    pip install numpy bpytop openwakeword ipython && \
-    conda clean -afy"
+### Install CUDA ############################################# START ####
+RUN wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
+RUN sudo apt-get install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb
+RUN rm libtinfo5_6.3-2ubuntu0.1_amd64.deb
 
+# Iterate over all the Ubuntu versions to find the latest CUDA version, starting from the most recent
+RUN for ubuntu_v in 2404 2204 2004; do \
+        # print the current CUDA version and Ubuntu version (useful if building with --progress=plain --no-cache option)
+        echo "Looking for CUDA version "$cuda_version" in Ubuntu $ubuntu_v"; \
+        echo "Looking into: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu$ubuntu_v/x86_64/"; \
+        # extract cuda major and minor versions from the full version string
+        CUDA_MAJOR=$(echo "$cuda_version" | cut -d. -f1) && CUDA_MINOR=$(echo "$cuda_version" | cut -d. -f2) && \
+        # get the latest version of the specified major and minor versions
+        CUDA_FILE=$(curl -s https://developer.download.nvidia.com/compute/cuda/repos/ubuntu$ubuntu_v/x86_64/ | grep -oP "(?<=href=')[^']+" | grep "^cuda-$CUDA_MAJOR-$CUDA_MINOR" | tail -1); \
+        if [ -n "$CUDA_FILE" ]; then \
+            echo "Found CUDA file: $CUDA_FILE"; \
+            # get the latest version of the keyring
+            CUDA_KEYRING=$(curl -s https://developer.download.nvidia.com/compute/cuda/repos/ubuntu$ubuntu_v/x86_64/ | grep -oP "(?<=href=')[^']+" | grep "^cuda-keyring" | tail -1); \
+            # download the keyring
+            wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu$ubuntu_v/x86_64/$CUDA_KEYRING; \
+            break; \
+        fi; \
+    done; \
+    # check if the CUDA version was found, otherwise exit
+    if [ -z "$CUDA_FILE" ]; then \
+        echo "CUDA version not found"; \
+        exit 1; \
+    fi
+
+# RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
+RUN sudo dpkg -i cuda-keyring*.deb
+RUN sudo apt-get update
+# RUN sudo apt-get upgrade -y
+RUN CUDA_MAJOR=$(echo "$cuda_version" | cut -d. -f1) && CUDA_MINOR=$(echo "$cuda_version" | cut -d. -f2) && \
+    sudo apt-get install -y cuda-toolkit-$CUDA_MAJOR-$CUDA_MINOR
+
+ENV PATH=/usr/local/cuda-$cuda_version/bin${PATH:+:${PATH}}
+ENV LD_LIBRARY_PATH=/usr/local/cuda-$cuda_version/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
+
+RUN rm cuda*
+### Install CUDA ############################################# END ####
+
+### Yarp related installations ############################### START ####
 # Build ycm
 USER ${robotology_install_user}
 WORKDIR ${robot_code}
@@ -131,59 +162,60 @@ RUN cd yarp && cd bindings &&  mkdir build && cd build && \
 # Install YARP completion
 RUN sudo ln -s /usr/local/share/bash-completion/completions/yarp /usr/share/bash-completion/completions
 
+##### Commented out since it does not seem to have an actual use (to be tested)
 #CER app
-RUN git clone --no-checkout --depth 1 --filter=blob:none https://github.com/robotology/cer && \
-    cd cer && git sparse-checkout init --cone && git sparse-checkout set app && git checkout && \
-    rm CMakeLists.txt && touch CMakeLists.txt && \
-    echo "# Copyright: (C) 2025 HSP Istituto Italiano di Tecnologia" > CMakeLists.txt && \
-    echo "# Authors: Ettore Landini" >> CMakeLists.txt && \
-    echo "# CopyPolicy: Released under the terms of the GNU GPL v2.0." >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "# Prepare a device library called \"cermod\"." >> CMakeLists.txt && \
-    echo "# A test executable called \"cermoddev\" will also be produced." >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "cmake_minimum_required(VERSION 3.5)" >> CMakeLists.txt && \
-    echo "project(CER LANGUAGES CXX C VERSION 1.0.0)" >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "set(VARS_PREFIX \"CER\")" >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "set(CMAKE_CXX_EXTENSIONS OFF)" >> CMakeLists.txt && \
-    echo "set(CMAKE_CXX_STANDARD 11)" >> CMakeLists.txt && \
-    echo "set(CMAKE_CXX_STANDARD_REQUIRED 11)" >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "set_property(GLOBAL PROPERTY USE_FOLDERS ON)" >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "list(APPEND CMAKE_MODULE_PATH \"\${CMAKE_SOURCE_DIR}/cmake\")" >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "find_package(YCM)" >> CMakeLists.txt && \
-    echo "find_package(YARP 3.11.100 REQUIRED COMPONENTS os sig dev math idl_tools)" >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "find_package(IPOPT)" >> CMakeLists.txt && \
-    echo "if(NOT IPOPT_FOUND)" >> CMakeLists.txt && \
-    echo "    message(WARNING \"IPOPT library was not found, some kinematics module will not be available.\")" >> CMakeLists.txt && \
-    echo "endif()" >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "include(GNUInstallDirs)" >> CMakeLists.txt && \
-    echo "set(CMAKE_RUNTIME_OUTPUT_DIRECTORY \"\${CMAKE_BINARY_DIR}/\${CMAKE_INSTALL_BINDIR}\")" >> CMakeLists.txt && \
-    echo "set(CMAKE_LIBRARY_OUTPUT_DIRECTORY \"\${CMAKE_BINARY_DIR}/\${CMAKE_INSTALL_LIBDIR}\")" >> CMakeLists.txt && \
-    echo "set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY \"\${CMAKE_BINARY_DIR}/\${CMAKE_INSTALL_LIBDIR}\")" >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "set(YARP_FORCE_DYNAMIC_PLUGINS TRUE CACHE INTERNAL \"\${PROJECT_NAME} is always built with dynamic plugins\")" >> CMakeLists.txt && \
-    echo "yarp_configure_external_installation(\${PROJECT_NAME} WITH_PLUGINS)" >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "include(AddInstallRPATHSupport)" >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "add_install_rpath_support(LIB_DIRS \"\${CMAKE_INSTALL_FULL_LIBDIR}\"" >> CMakeLists.txt && \
-    echo "                          BIN_DIRS \"\${CMAKE_INSTALL_FULL_BINDIR}\"" >> CMakeLists.txt && \
-    echo "                                   \"\${CMAKE_INSTALL_PREFIX}/\${CER_DYNAMIC_PLUGINS_INSTALL_DIR}\"" >> CMakeLists.txt && \
-    echo "                          USE_LINK_PATH)" >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "# Everything is configured now, we can start adding source code" >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "add_subdirectory(app)" >> CMakeLists.txt && \
-    echo "" >> CMakeLists.txt && \
-    echo "include(AddUninstallTarget)" >> CMakeLists.txt && \
-    cmake -S . -B build
+# RUN git clone --no-checkout --depth 1 --filter=blob:none https://github.com/robotology/cer && \
+#     cd cer && git sparse-checkout init --cone && git sparse-checkout set app && git checkout && \
+#     rm CMakeLists.txt && touch CMakeLists.txt && \
+#     echo "# Copyright: (C) 2025 HSP Istituto Italiano di Tecnologia" > CMakeLists.txt && \
+#     echo "# Authors: Ettore Landini" >> CMakeLists.txt && \
+#     echo "# CopyPolicy: Released under the terms of the GNU GPL v2.0." >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "# Prepare a device library called \"cermod\"." >> CMakeLists.txt && \
+#     echo "# A test executable called \"cermoddev\" will also be produced." >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "cmake_minimum_required(VERSION 3.5)" >> CMakeLists.txt && \
+#     echo "project(CER LANGUAGES CXX C VERSION 1.0.0)" >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "set(VARS_PREFIX \"CER\")" >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "set(CMAKE_CXX_EXTENSIONS OFF)" >> CMakeLists.txt && \
+#     echo "set(CMAKE_CXX_STANDARD 11)" >> CMakeLists.txt && \
+#     echo "set(CMAKE_CXX_STANDARD_REQUIRED 11)" >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "set_property(GLOBAL PROPERTY USE_FOLDERS ON)" >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "list(APPEND CMAKE_MODULE_PATH \"\${CMAKE_SOURCE_DIR}/cmake\")" >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "find_package(YCM)" >> CMakeLists.txt && \
+#     echo "find_package(YARP 3.11.100 REQUIRED COMPONENTS os sig dev math idl_tools)" >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "find_package(IPOPT)" >> CMakeLists.txt && \
+#     echo "if(NOT IPOPT_FOUND)" >> CMakeLists.txt && \
+#     echo "    message(WARNING \"IPOPT library was not found, some kinematics module will not be available.\")" >> CMakeLists.txt && \
+#     echo "endif()" >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "include(GNUInstallDirs)" >> CMakeLists.txt && \
+#     echo "set(CMAKE_RUNTIME_OUTPUT_DIRECTORY \"\${CMAKE_BINARY_DIR}/\${CMAKE_INSTALL_BINDIR}\")" >> CMakeLists.txt && \
+#     echo "set(CMAKE_LIBRARY_OUTPUT_DIRECTORY \"\${CMAKE_BINARY_DIR}/\${CMAKE_INSTALL_LIBDIR}\")" >> CMakeLists.txt && \
+#     echo "set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY \"\${CMAKE_BINARY_DIR}/\${CMAKE_INSTALL_LIBDIR}\")" >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "set(YARP_FORCE_DYNAMIC_PLUGINS TRUE CACHE INTERNAL \"\${PROJECT_NAME} is always built with dynamic plugins\")" >> CMakeLists.txt && \
+#     echo "yarp_configure_external_installation(\${PROJECT_NAME} WITH_PLUGINS)" >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "include(AddInstallRPATHSupport)" >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "add_install_rpath_support(LIB_DIRS \"\${CMAKE_INSTALL_FULL_LIBDIR}\"" >> CMakeLists.txt && \
+#     echo "                          BIN_DIRS \"\${CMAKE_INSTALL_FULL_BINDIR}\"" >> CMakeLists.txt && \
+#     echo "                                   \"\${CMAKE_INSTALL_PREFIX}/\${CER_DYNAMIC_PLUGINS_INSTALL_DIR}\"" >> CMakeLists.txt && \
+#     echo "                          USE_LINK_PATH)" >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "# Everything is configured now, we can start adding source code" >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "add_subdirectory(app)" >> CMakeLists.txt && \
+#     echo "" >> CMakeLists.txt && \
+#     echo "include(AddUninstallTarget)" >> CMakeLists.txt && \
+#     cmake -S . -B build
 
 #R1_OBJECT_RETRIEVAL app
 RUN git clone --no-checkout --filter=blob:none https://github.com/hsp-iit/r1-object-retrieval && \
@@ -303,8 +335,81 @@ ENV TOUR_GUIDE_ROBOT_SOURCE_DIR=${robot_code}/tour-guide-robot \
     YARP_DATA_DIRS=${YARP_DATA_DIRS}:${robot_code}/tour-guide-robot/build/share/tour-guide-robot \
     PATH=${PATH}:${robot_code}/tour-guide-robot/build/bin
 
-RUN echo "conda activate openwakeword" >> /home/${user_name}/.bashrc && \
+
+### Miniforge and Python environment ############################## START ####
+USER ${robotology_install_user}
+WORKDIR ${yarp_user_home}
+RUN wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
+RUN /bin/bash -c "bash ${yarp_user_home}/Miniforge3-$(uname)-$(uname -m).sh -b"
+RUN ${yarp_user_home}/miniforge3/bin/conda init
+RUN /bin/bash -c "source ${yarp_user_home}/miniforge3/etc/profile.d/conda.sh && \
+    conda env create -y -f ${TOUR_GUIDE_ROBOT_SOURCE_DIR}/docker_stuff/docker_talk/environment.yml && \
+    conda clean -afy"
+### Miniforge and Python environment ############################## END ####
+
+### Install openWakeWord and voicebox python packages ############################## START ####
+USER ${robotology_install_user}
+WORKDIR ${yarp_user_home}
+RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+RUN curl -fsSL https://bun.sh/install | bash
+RUN sudo apt update && sudo apt install -y just libwebkit2gtk-4.1-dev \
+  file \
+  libxdo-dev \
+  libssl-dev \
+  libayatana-appindicator3-dev \
+  librsvg2-dev
+WORKDIR ${robot_code}
+RUN git clone https://github.com/dscripka/openWakeWord && cd openWakeWord && \
+    /bin/bash -c "source ${yarp_user_home}/miniforge3/etc/profile.d/conda.sh && \
+    conda activate unified-voice-pipeline && \
+    pip install ."
+RUN git clone https://github.com/jamiepine/voicebox.git && cd voicebox && \
+    /bin/bash -c "source ${yarp_user_home}/miniforge3/etc/profile.d/conda.sh && \
+    conda activate unified-voice-pipeline && \
+    just setup && just build"
+### Install openWakeWord and voicebox python packages ############################## END ####
+
+### Install whisper.cpp ############################### START ####
+WORKDIR ${robot_code}
+RUN git clone https://github.com/ggml-org/whisper.cpp && \
+    cd whisper.cpp && cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${yarp-user_home}/userInstalled \
+    -DGGML_CUDA=ON && \
+    cmake --build build -j8 && cmake --build build --target install
+ENV whisper_DIR=${yarp_user_home}/userInstalled \
+    LD_LIBRARY_PATH=${yarp_user_home}/userInstalled/lib:${LD_LIBRARY_PATH}
+### Install whisper.cpp ############################### END ####
+
+### Offline vocal interaction devices ################################ START ####
+WORKDIR ${robot_code}
+RUN git clone https://github.com/elandini84/yarp-device-speechTranscription-whisper -b refactor/general_update && \
+    cd yarp-device-speechTranscription-whisper && \
+    cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -Dwhisper_DIR=${yarp-user_home}/userInstalled && \
+    cmake --build build -j8
+RUN git clone https://github.com/robotology/yarp-device-voicebox && \
+    cd yarp-device-voicebox && \
+    cmake -B build -S . -DCMAKE_BUILD_TYPE=Release && \
+    cmake --build build -j8
+RUN git clone https://github.com/robotology/yarp-device-llama2 && \
+    cd yarp-device-llama2 && \
+    ./setup_submodule.sh && \
+    cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DLLAMA_ALL_WARNINGS=ON \
+    -DGGML_CUDA=ON -DLLAMA_BUILD_COMMON=ON \
+    -DLLAMA_BUILD_EXAMPLES=ON -DLLAMA_BUILD_SERVER=ON && \
+    cmake --build build -j8
+ENV YARP_DATA_DIRS=${YARP_DATA_DIRS}:${robot_code}/yarp-device-speechTranscription-whisper/build/share/yarp:${robot_code}/yarp-device-voicebox/build/share/yarp:${robot_code}/yarp-device-llama2/build/share/yarp \
+    PATH=${PATH}:${robot_code}/yarp-device-speechTranscription-whisper/build/bin:${robot_code}/yarp-device-voicebox/build/bin:${robot_code}/yarp-device-llama2/build/bin
+### Offline vocal interaction devices ################################ END ####
+
+### YARP MCP repos ############################################# START ####
+WORKDIR ${robot_code}
+RUN git clone https://github.com/hsp-iit/yarp-mcpServers.git && \
+    git clone https://github.com/hsp-iit/yarp-mcpClient-generalPurpose.git
+ENV YARP_DATA_DIRS=${YARP_DATA_DIRS}:${robot_code}/yarp-mcpClient-generalPurpose/resources:${robot_code}/yarp-mcpServers/resources
+### YARP MCP repos ############################################# END ####
+
+
+RUN echo "conda activate unified-voice-pipeline" >> /home/${user_name}/.bashrc && \
     sed -i '/^case \$- in$/,/^esac$/s/^/#/' /home/${user_name}/.bashrc
 
 WORKDIR ${yarp_user_home}
-CMD bash && conda activate openwakeword
+CMD bash && conda activate unified-voice-pipeline
