github actions improvements

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,9 +28,30 @@ jobs:
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build the Docker image
       working-directory: docker_stuff/docker_core2/
-      run: ./build-docker.sh
+      run: |
+       if [ ${{ github.event_name }} == 'schedule' ]; then
+          echo "Building development image"
+          sudo docker build --tag elandini84/r1images:r1Core2_devel .
+       elif [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
+          echo "Building stable image"
+          sudo docker build --tag elandini84/r1images:r1Core2_stable .
+       else
+          echo "Failure!"
+          exit 1
+       fi
     - name: Push image
-      run: docker push elandini84/r1images:r1Core2
+      run: |
+       if [ ${{ github.event_name }} == 'schedule' ]; then
+          echo "Pushing development image"
+          docker push elandini84/r1images:r1Core2_devel
+       elif [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
+          echo "Pushing stable image"
+          docker push elandini84/r1images:r1Core2_stable
+       else
+          echo "Failure!"
+          exit 1
+       fi
+
 
 ################################################################## Currently runs OOM as the diffult containers for linux are 7Gb of RAM.
 #   build-r1Sim2:
